name: ci

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]

jobs:
  build-test:
    runs-on: ubuntu-${{ matrix.ubuntu }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu: ["22.04", "24.04"]
    env:
      OMPI_MCA_rmaps_base_oversubscribe: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            pkg-config \
            openmpi-bin \
            libopenmpi-dev
          sudo apt-get install -y libpetsc-real-dev || sudo apt-get install -y libpetsc-dev petsc-dev

      - name: Install Catch2 v3
        run: |
          script/install_catch2v3.sh "$HOME/usr"

      - name: Build, and test
        run: |
          export PICNIX_CATCH2_CONFIG="$HOME/usr/lib/cmake/Catch2/Catch2Config.cmake"
          cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_CXX_COMPILER=mpicxx \
            -DPICNIX_CATCH2_CONFIG="$PICNIX_CATCH2_CONFIG"
          cmake --build build --parallel
          ctest --test-dir build --output-on-failure

      - name: Build and test elliptic
        run: |
          export PICNIX_CATCH2_CONFIG="$HOME/usr/lib/cmake/Catch2/Catch2Config.cmake"
          cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_CXX_COMPILER=mpicxx \
            -DPICNIX_CATCH2_CONFIG="$PICNIX_CATCH2_CONFIG"
          cmake --build build --parallel
          ctest --test-dir build --output-on-failure
        working-directory: elliptic
